ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/proxy-next-upstream: "error timeout http_502"
    nginx.ingress.kubernetes.io/proxy-next-upstream-tries: "3"
    nginx.ingress.kubernetes.io/use-regex: "true"
    # Cache Configuration
    nginx.ingress.kubernetes.io/proxy-cache: "true"
    nginx.ingress.kubernetes.io/proxy-cache-path: "/var/cache/nginx keys_zone=STATIC:10m inactive=7d use_temp_path=off"
    # HTTP/2
    nginx.ingress.kubernetes.io/use-http2: "true"
    nginx.ingress.kubernetes.io/add-headers: |
      Vary: Accept-Encoding
    nginx.ingress.kubernetes.io/use-gzip: "true"
    nginx.ingress.kubernetes.io/gzip-level: "6"
    nginx.ingress.kubernetes.io/gzip-min-length: "1024"
    nginx.ingress.kubernetes.io/gzip-types: "application/javascript application/json text/plain text/css application/x-javascript text/xml application/xml application/xml+rss text/javascript"
    nginx.org/server-snippets: |
      location ~ ^/product-feedback-app/assets/(.*) {
        rewrite ^/product-feedback-app/assets/(.*) /assets/$1 break;
        proxy_pass http://product-feedback-app-svc:4000;
      }

      location /product-feedback-app {
        proxy_pass http://product-feedback-app-svc:4000/product-feedback-app;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
      }
  maxBodySize: "8m"
  timeout:
    connect: "5"
    read: "60"
    send: "60"

  domain: alexbartleynees.com

  namespace: default

  services:
    - name: product-feedback-app
      path: /product-feedback-app
      pathType: Prefix
      serviceName: product-feedback-app-svc
      servicePort: 4000
      annotations:
        nginx.ingress.kubernetes.io/configuration-snippet: |
          add_header Cache-Control "public, max-age=3600";

tls:
  enabled: true
  secretName: website-tls
